[theme]
primaryColor = "#00695c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f8e9"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = false
showWarningOnDirectExecution = false

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
